<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <ProjectReference Include="..\RateLimitEngine.Core\RateLimitEngine.Core.csproj" />
    <ProjectReference Include="..\RateLimitEngine.Algorithms\RateLimitEngine.Algorithms.csproj" />
    <ProjectReference Include="..\RateLimitEngine.Redis\RateLimitEngine.Redis.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>RateLimitEngine.AspNetCore</PackageId>
    <Description>ASP.NET Core middleware integration for RateLimitEngine with in-memory and Redis-backed rate limiting.</Description>
    <PackageTags>rate-limiting;rate-limit;aspnetcore;middleware;redis;distributed;dotnet</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md"
          Pack="true"
          PackagePath="README.md" />
  </ItemGroup>

</Project>
